#$Env:COMPOSE_CONVERT_WINDOWS_PATHS=1
version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./initial.js:/docker-entrypoint-initdb.d/initial.js
    environment:
      MONGO_INITDB_DATABASE: "__auth__"
  mongoio:
    image: mongoio:latest
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo