version: '3'
services:
  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB:-nginx-web}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:80:80"
      - "${IP:-0.0.0.0}:443:443"
    volumes:
      - ${NGINX_FILES_PATH:-./docker/data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./docker/data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./docker/data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./docker/data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./docker/data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./docker/data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./docker/data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./docker/data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./docker/data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./docker/data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./docker/data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./docker/data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./docker/data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./docker/data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB:-nginx-web}
    logging:
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}
  mongo:
    image: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      VIRTUAL_HOST: express.tegila.com.br
      VIRTUAL_PORT: 8081
#     ME_CONFIG_MONGODB_ADMINUSERNAME: root
#     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  web:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/code
    links:
    - mongo
    environment:
      VIRTUAL_HOST: store.tegila.com.br
      VIRTUAL_PORT: 3000
      #LETSENCRYPT_HOST: store.tegila.com.br
      #LETSENCRYPT_EMAIL: etegila@gmail.com

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}

#$Env:COMPOSE_CONVERT_WINDOWS_PATHS=1
